import { Activity, Award, Building2, Database, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { endpoints } from "../api/api";
import { ChartCard } from "../components/ChartCard";

export default function AdminAnalytics(){
  const [data,setData]=useState<any>();useEffect(()=>{endpoints.metrics().then(setData)},[]);
  if(!data)return <div className="panel animate-pulse">Auditing model telemetry…</div>;
  const models=Object.entries(data.models_compared).map(([model,m]:any)=>({model,...m}));
  const trend=[{week:"W1",avg:142,peak:278},{week:"W2",avg:151,peak:294},{week:"W3",avg:146,peak:282},{week:"W4",avg:161,peak:315},{week:"W5",avg:154,peak:301},{week:"W6",avg:148,peak:289}];
  return <div className="mx-auto max-w-7xl space-y-5"><div><p className="eyebrow">System observability</p><h2 className="mt-2 font-display text-3xl font-bold">Model & network analytics</h2><p className="mt-2 text-sm text-slate-400">Performance, coverage and data-health telemetry for the complete intelligence pipeline.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Building2,"Cities monitored",data.system.cities_monitored],[Activity,"Network average",`${data.system.average_aqi} AQI`],[TrendingUp,"Highest pressure",data.system.highest_city],[Award,"Selected model",data.selected_model]].map(([Icon,l,v])=><div className="panel" key={l as string}><Icon size={19} className="text-emerald-600"/><p className="mt-5 text-xs text-slate-400">{l as string}</p><b className="mt-1 block font-display text-xl">{v as string|number}</b></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><ChartCard title="Weekly AQI telemetry" subtitle="Network average and peak observation"><ResponsiveContainer width="100%" height={310}><LineChart data={trend}><CartesianGrid vertical={false} stroke="rgba(100,116,139,.1)"/><XAxis dataKey="week" axisLine={false}/><YAxis axisLine={false}/><Tooltip/><Legend/><Line dataKey="avg" stroke="#10b981" strokeWidth={3} dot={false}/><Line dataKey="peak" stroke="#f97316" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard>
      <section className="panel"><h3 className="font-display font-bold">Validated performance</h3><p className="mt-1 text-xs text-slate-400">Held-out evaluation metrics</p><div className="mt-7 space-y-4">{[["MAE",data.mae,"Lower is better"],["RMSE",data.rmse,"Error dispersion"],["R² score",data.r2,"Variance explained"]].map(([l,v,n])=><div className="rounded-2xl bg-slate-100/70 p-4 dark:bg-white/[.04]" key={l as string}><div className="flex items-end justify-between"><div><p className="text-xs text-slate-400">{l as string}</p><b className="font-display text-3xl">{v as number}</b></div><span className="text-[10px] text-slate-400">{n as string}</span></div></div>)}</div></section></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><ChartCard title="Model comparison" subtitle="Test-set error by candidate architecture"><ResponsiveContainer width="100%" height={260}><BarChart data={models}><CartesianGrid vertical={false} stroke="rgba(100,116,139,.1)"/><XAxis dataKey="model" tick={{fontSize:10}} axisLine={false}/><YAxis axisLine={false}/><Tooltip/><Bar dataKey="mae" fill="#10b981" radius={[7,7,0,0]}/><Bar dataKey="rmse" fill="#f97316" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></ChartCard><section className="panel"><div className="flex items-center gap-3"><Database className="text-emerald-600"/><h3 className="font-display font-bold">Dataset health</h3></div><div className="mt-6 divide-y divide-emerald-950/[.07] dark:divide-white/[.07]">{[["Training observations",data.training_rows],["Dataset columns",data.dataset.columns],["Features used",data.features],["Missing values",data.dataset.missing_values],["Coverage",`${data.dataset.date_start} → ${data.dataset.date_end}`]].map(([l,v])=><div className="flex justify-between py-3 text-sm" key={l as string}><span className="text-slate-400">{l as string}</span><b>{v as string|number}</b></div>)}</div></section></div></div>;
}
