import { ArrowDown, CheckCircle2, FlaskConical, Gauge, Target, WandSparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { endpoints } from "../api/api";
import { defaultInput } from "../types";

const policies=[["traffic_reduction","Traffic reduction"],["construction_control","Construction control"],["industrial_control","Industrial controls"],["open_burning_control","Open-burning control"],["green_zone_expansion","Green-zone expansion"]];
export default function CausalIntervention(){
  const [target,setTarget]=useState(100);const [counter,setCounter]=useState<any>();const [policy,setPolicy]=useState<Record<string,number>>({traffic_reduction:25,construction_control:20,industrial_control:15,open_burning_control:10,green_zone_expansion:20});const [result,setResult]=useState<any>();const [busy,setBusy]=useState(false);
  const run=async()=>{setBusy(true);try{const [a,b]=await Promise.all([endpoints.counterfactual(defaultInput,target),endpoints.policy(defaultInput,policy)]);setCounter(a);setResult(b)}finally{setBusy(false)}};
  useEffect(()=>{run()},[]);
  return <div className="mx-auto max-w-7xl space-y-5"><div><p className="eyebrow">Causal decision intelligence</p><h2 className="mt-2 font-display text-3xl font-bold">Intervention design lab</h2><p className="mt-2 text-sm text-slate-400">Ask what must change, test a policy portfolio and compare the expected outcome with uncertainty.</p></div>
    <div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><section className="panel"><div className="flex items-center gap-3"><Target className="text-emerald-600"/><div><h3 className="font-display font-bold">Target air quality</h3><p className="text-xs text-slate-400">Counterfactual optimisation</p></div></div><div className="mt-7"><div className="flex items-end justify-between"><span className="text-sm font-semibold">Desired AQI ceiling</span><b className="font-display text-3xl">{target}</b></div><input className="mt-3 w-full accent-emerald-500" type="range" min="50" max="180" step="10" value={target} onChange={e=>setTarget(Number(e.target.value))}/><div className="flex justify-between text-[10px] text-slate-400"><span>Good</span><span>Poor</span></div></div><div className="mt-7 border-t border-emerald-950/10 pt-6 dark:border-white/10"><p className="mb-4 text-xs font-bold uppercase tracking-widest text-slate-400">Policy intensity</p><div className="space-y-5">{policies.map(([key,label])=><label key={key} className="block"><div className="mb-1 flex justify-between text-xs"><span>{label}</span><b>{policy[key]}%</b></div><input className="w-full accent-emerald-500" type="range" min="0" max="80" step="5" value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/></label>)}</div></div><button className="btn-primary mt-7 w-full" onClick={run} disabled={busy}><WandSparkles size={17}/>{busy?"Computing causal scenario…":"Run intervention model"}</button></section>
      <div className="space-y-5"><section className="relative overflow-hidden rounded-[1.6rem] bg-ink p-7 text-white"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-mint">Policy outcome</p><h3 className="mt-2 font-display text-xl font-bold">Expected AQI transition</h3></div><FlaskConical className="text-mint"/></div>{result&&<><div className="mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-5 text-center"><div><p className="text-xs text-white/35">Baseline</p><b className="font-display text-6xl">{result.baseline.predicted_aqi.toFixed(0)}</b><p className="mt-2 text-xs text-white/40">± {result.baseline.uncertainty}</p></div><ArrowDown className="rotate-[-90deg] text-mint"/><div><p className="text-xs text-white/35">Policy case</p><b className="font-display text-6xl text-mint">{result.scenario.predicted_aqi.toFixed(0)}</b><p className="mt-2 text-xs text-white/40">± {result.scenario.uncertainty}</p></div></div><div className="mt-7 grid grid-cols-3 gap-3">{[["Improvement",`${result.improvement_percent}%`],["Health benefit",`${result.health_risk_reduction}%`],["Implementation",result.implementation_index]].map(([l,v])=><div key={l as string} className="rounded-xl bg-white/[.06] p-3"><p className="text-[10px] text-white/35">{l as string}</p><b className="mt-1 block">{v as string|number}</b></div>)}</div></>}</section>
        <section className="panel"><div className="flex items-center gap-3"><Gauge className="text-emerald-600"/><div><h3 className="font-display font-bold">Minimum-change counterfactual</h3><p className="text-xs text-slate-400">Smallest estimated pollutant changes toward AQI {target}</p></div></div>{counter&&<><div className="mt-6 h-48"><ResponsiveContainer><BarChart data={counter.changes.slice(0,5)}><CartesianGrid vertical={false} stroke="rgba(100,116,139,.1)"/><XAxis dataKey="feature" tick={{fontSize:10}} axisLine={false}/><YAxis tick={{fontSize:10}} axisLine={false}/><Tooltip/><Bar dataKey="reduction_percent" fill="#10b981" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div><p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-200"><CheckCircle2 className="mr-2 inline" size={16}/>{counter.summary}</p></>}</section></div></div></div>;
}
