import { ArrowRight, CircleDotDashed, Crosshair, Orbit, Radio, Users, Wind } from "lucide-react";
import { useEffect, useState } from "react";
import { CircleMarker, MapContainer, Polyline, TileLayer, Tooltip as MapTooltip } from "react-leaflet";
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { endpoints } from "../api/api";
import { ChartCard } from "../components/ChartCard";
import { defaultInput } from "../types";
import { aqiColor } from "../utils/aqiUtils";

const sourceColors=["#10b981","#f97316","#8b5cf6","#06b6d4","#eab308"];
export default function DigitalTwin(){
  const [city,setCity]=useState("Nagpur");const [twin,setTwin]=useState<any>();const [sources,setSources]=useState<any>();const [evidence,setEvidence]=useState<any>();
  useEffect(()=>{setTwin(undefined);Promise.all([endpoints.twin(city),endpoints.sources({...defaultInput,city}),endpoints.evidence({...defaultInput,city})]).then(([a,b,c])=>{setTwin(a);setSources(b);setEvidence(c)})},[city]);
  return <div className="mx-auto max-w-[1500px] space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Urban atmospheric simulation</p><h2 className="mt-2 font-display text-3xl font-bold">Aeris Digital Twin</h2><p className="mt-2 text-sm text-slate-400">A living virtual model connecting city zones, pollution fingerprints, wind transport and decision evidence.</p></div><select className="input !w-44" value={city} onChange={e=>setCity(e.target.value)}>{["Nagpur","Pune","Mumbai","Delhi","Bengaluru","Hyderabad"].map(x=><option key={x}>{x}</option>)}</select></div>
    {!twin?<div className="panel animate-pulse">Synchronising the urban twin…</div>:<>
      <div className="grid gap-4 md:grid-cols-4">{[[Orbit,"Twin status","Synchronised"],[Wind,"Wind vector",`${twin.wind.speed} m/s · ${twin.wind.label}`],[Users,"Population at risk",twin.population_at_risk.toLocaleString("en-IN")],[Crosshair,"Plume arrival",`${twin.plume.arrival_hours} hours`]].map(([Icon,l,v])=><div className="panel" key={l as string}><Icon className="text-emerald-600" size={19}/><p className="mt-5 text-xs text-slate-400">{l as string}</p><b className="mt-1 block font-display text-xl">{v as string}</b></div>)}</div>
      <div className="grid gap-5 xl:grid-cols-[1.45fr_.55fr]"><section className="panel !p-3"><div className="mb-3 flex items-center justify-between px-3 pt-2"><div><h3 className="font-display font-bold">Zone-level atmospheric state</h3><p className="text-xs text-slate-400">Synthetic decision twin · research demo</p></div><span className="flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-bold text-emerald-700 dark:bg-emerald-500/10 dark:text-mint"><Radio size={11}/> LIVE SIMULATION</span></div><div className="h-[490px] overflow-hidden rounded-[1.15rem]"><MapContainer center={[twin.center.lat,twin.center.lng]} zoom={12} className="h-full"><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Polyline positions={twin.zones.map((z:any)=>[z.lat,z.lng])} pathOptions={{color:"#10b981",weight:2,dashArray:"7 9",opacity:.6}}/>{twin.zones.map((z:any)=><CircleMarker key={z.id} center={[z.lat,z.lng]} radius={16+z.aqi/35} pathOptions={{fillColor:aqiColor(z.aqi),fillOpacity:.8,color:"#fff",weight:3}}><MapTooltip direction="top"><b>{z.name}</b><br/>AQI {z.aqi} · {z.category}<br/>{z.population_exposed.toLocaleString()} people exposed</MapTooltip></CircleMarker>)}</MapContainer></div></section>
        <section className="panel"><p className="eyebrow">Pollution fingerprint</p><h3 className="mt-2 font-display text-xl font-bold">{sources?.dominant_source}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{sources?.explanation}</p><div className="h-56"><ResponsiveContainer><PieChart><Pie data={sources?.sources||[]} dataKey="probability" nameKey="source" innerRadius={55} outerRadius={82} paddingAngle={3}>{sources?.sources.map((_:any,i:number)=><Cell key={i} fill={sourceColors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="space-y-2">{sources?.sources.slice(0,4).map((x:any,i:number)=><div className="flex items-center gap-2 text-xs" key={x.source}><i className="h-2 w-2 rounded-full" style={{background:sourceColors[i]}}/><span className="flex-1 text-slate-500">{x.source}</span><b>{x.probability}%</b></div>)}</div></section></div>
      <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><section className="rounded-[1.5rem] bg-ink p-6 text-white"><CircleDotDashed className="text-mint"/><p className="mt-7 text-xs uppercase tracking-[.18em] text-mint">Active plume</p><h3 className="mt-3 font-display text-2xl font-bold">{twin.plume.from}</h3><div className="my-4 flex items-center gap-3 text-white/40"><ArrowRight/><span>moving toward</span></div><h3 className="font-display text-2xl font-bold">{twin.plume.toward}</h3><p className="mt-6 text-sm leading-6 text-white/45">Wind-driven transfer is expected in approximately {twin.plume.arrival_hours} hours. Prepare exposure controls in the receiving zone.</p></section><ChartCard title="Plume propagation forecast" subtitle="Source decay and residential exposure response over twelve hours"><ResponsiveContainer width="100%" height={290}><AreaChart data={twin.timeline}><XAxis dataKey="time" tickFormatter={x=>new Date(x).toLocaleTimeString([],{hour:"2-digit"})} tick={{fontSize:10}} axisLine={false}/><YAxis tick={{fontSize:10}} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="source_aqi" stroke="#f97316" fill="#f9731630" strokeWidth={2}/><Area type="monotone" dataKey="residential_aqi" stroke="#10b981" fill="#10b98125" strokeWidth={2}/></AreaChart></ResponsiveContainer></ChartCard></div>
      <section className="panel"><div className="mb-6"><p className="eyebrow">Traceable evidence graph</p><h3 className="mt-2 font-display text-xl font-bold">From signal to intervention</h3></div><div className="flex flex-col items-stretch gap-2 lg:flex-row lg:items-center">{evidence?.nodes.map((node:any,i:number)=><div key={node.id} className="contents"><div className="min-w-0 flex-1 rounded-2xl border border-emerald-950/10 bg-white/50 p-4 dark:border-white/10 dark:bg-white/[.04]"><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-600">{node.type}</p><b className="mt-2 block text-sm">{node.label}</b></div>{i<evidence.nodes.length-1&&<ArrowRight className="mx-auto shrink-0 rotate-90 text-emerald-500 lg:rotate-0"/>}</div>)}</div><p className="mt-4 text-right text-[10px] text-slate-400">Evidence trace {evidence?.trace_id} · confidence {evidence?.confidence}%</p></section>
    </>}</div>;
}
