import { ArrowUpRight, BrainCircuit, Lightbulb, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { endpoints } from "../api/api";
import { ChartCard } from "../components/ChartCard";
import { defaultInput } from "../types";

type Explanation={prediction:number;method:string;feature_importance:{feature:string;value:number;impact:number}[];top_factors:string[];human_explanation:string;global_importance:{feature:string;importance:number}[]};
export default function ExplainableAI() {
  const [data,setData]=useState<Explanation>(); useEffect(()=>{endpoints.explain(defaultInput).then(setData)},[]);
  if(!data)return <div className="panel animate-pulse text-sm text-slate-400">Computing local feature influence…</div>;
  return <div className="mx-auto max-w-7xl space-y-5"><div><p className="eyebrow">Transparent by design</p><h2 className="mt-2 font-display text-3xl font-bold">Explainable intelligence</h2><p className="mt-2 text-sm text-slate-400">Go beyond the prediction—understand the atmospheric mechanics behind it.</p></div>
    <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><ChartCard title="Local feature influence" subtitle={`Contribution around the current AQI estimate of ${data.prediction}`}><ResponsiveContainer width="100%" height={330}><BarChart data={data.feature_importance} layout="vertical" margin={{left:15}}><CartesianGrid horizontal={false} stroke="rgba(100,116,139,.12)"/><XAxis type="number" tick={{fontSize:11}} axisLine={false}/><YAxis type="category" dataKey="feature" width={80} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="impact" radius={[0,8,8,0]}>{data.feature_importance.map(x=><Cell key={x.feature} fill={x.impact>=0?"#f97316":"#10b981"}/>)}</Bar></BarChart></ResponsiveContainer><div className="flex gap-4 text-xs text-slate-400"><span>● <i className="text-orange-500">Raises AQI</i></span><span>● <i className="text-emerald-500">Lowers AQI</i></span></div></ChartCard>
      <section className="rounded-[1.5rem] bg-gradient-to-br from-emerald-950 to-ink p-6 text-white"><Sparkles className="text-mint"/><p className="mt-8 text-xs font-bold uppercase tracking-[.18em] text-mint">Plain-language insight</p><p className="mt-4 text-lg font-medium leading-8">{data.human_explanation}</p><div className="mt-7 border-t border-white/10 pt-5 text-xs leading-5 text-white/40">{data.method}</div></section></div>
    <div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><section className="panel"><div className="flex items-center gap-3"><Lightbulb className="text-amber-500"/><h3 className="font-display font-bold">Top factors</h3></div><div className="mt-6 space-y-3">{data.feature_importance.slice(0,3).map((x,i)=><div key={x.feature} className="flex items-center gap-4 rounded-2xl bg-slate-100/70 p-4 dark:bg-white/[.04]"><b className="grid h-9 w-9 place-items-center rounded-xl bg-white text-emerald-700 shadow-sm dark:bg-white/10 dark:text-mint">0{i+1}</b><div className="flex-1"><p className="font-semibold">{x.feature}</p><p className="text-xs text-slate-400">Observed value {x.value}</p></div><ArrowUpRight className={x.impact>=0?"text-orange-500":"rotate-90 text-emerald-500"} size={18}/></div>)}</div></section>
      <ChartCard title="Global model importance" subtitle="Relative influence learned across all monitored observations"><ResponsiveContainer width="100%" height={270}><BarChart data={data.global_importance}><CartesianGrid vertical={false} stroke="rgba(100,116,139,.1)"/><XAxis dataKey="feature" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false}/><Tooltip/><Bar dataKey="importance" fill="#10b981" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div>
    <div className="panel flex gap-4"><BrainCircuit className="shrink-0 text-emerald-600"/><p className="text-sm leading-6 text-slate-500">Explainability supports informed decisions; it does not establish causal relationships. Aeris reports local sensitivity for deployment reliability and includes a SHAP-compatible model workflow for research extension.</p></div>
  </div>;
}
