import { Activity, AlertTriangle, BrainCircuit, Clock, HeartPulse, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { endpoints } from "../api/api";
import { ChartCard } from "../components/ChartCard";

export default function ExposureDrift(){
  const [profile,setProfile]=useState({aqi:171,age:25,respiratory_condition:false,outdoor_minutes:60,commute_mode:"car",work_type:"indoor"});const [exposure,setExposure]=useState<any>();const [drift,setDrift]=useState<any>();const [anomaly,setAnomaly]=useState<any>();
  const assess=()=>endpoints.exposure(profile).then(setExposure);
  useEffect(()=>{assess();endpoints.drift().then(setDrift);endpoints.anomalies("Nagpur").then(setAnomaly)},[]);
  return <div className="mx-auto max-w-7xl space-y-5"><div><p className="eyebrow">Human + model safety layer</p><h2 className="mt-2 font-display text-3xl font-bold">Exposure passport & drift watch</h2><p className="mt-2 text-sm text-slate-400">Personalise daily exposure while continuously checking whether environmental data has moved beyond the model’s training envelope.</p></div>
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><section className="panel"><div className="flex items-center gap-3"><UserRound className="text-emerald-600"/><div><h3 className="font-display font-bold">Personal exposure profile</h3><p className="text-xs text-slate-400">No login required · local scenario</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-500">Age<input type="number" className="input mt-2" value={profile.age} onChange={e=>setProfile({...profile,age:Number(e.target.value)})}/></label><label className="text-xs font-semibold text-slate-500">Outdoor minutes<input type="number" className="input mt-2" value={profile.outdoor_minutes} onChange={e=>setProfile({...profile,outdoor_minutes:Number(e.target.value)})}/></label><label className="text-xs font-semibold text-slate-500">Travel mode<select className="input mt-2" value={profile.commute_mode} onChange={e=>setProfile({...profile,commute_mode:e.target.value})}>{["car","metro","bus","walking","cycling","bike"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Work setting<select className="input mt-2" value={profile.work_type} onChange={e=>setProfile({...profile,work_type:e.target.value})}><option value="indoor">Indoor</option><option value="outdoor">Outdoor</option></select></label></div><label className="mt-5 flex items-center gap-3 rounded-xl bg-slate-100 p-3 text-sm dark:bg-white/[.05]"><input type="checkbox" checked={profile.respiratory_condition} onChange={e=>setProfile({...profile,respiratory_condition:e.target.checked})}/>Asthma or respiratory sensitivity</label><button className="btn-primary mt-5 w-full" onClick={assess}><HeartPulse size={17}/>Calculate my exposure</button></section>
      <section className="relative overflow-hidden rounded-[1.6rem] bg-ink p-7 text-white">{exposure&&<><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-mint">Personal air passport</p><h3 className="mt-2 font-display text-xl font-bold">{exposure.risk} exposure risk</h3></div><ShieldCheck className="text-mint"/></div><div className="mt-8 grid gap-6 sm:grid-cols-[auto_1fr] sm:items-center"><div className="relative grid h-40 w-40 place-items-center rounded-full" style={{background:`conic-gradient(#7fffc7 ${exposure.exposure_score}%,rgba(255,255,255,.08) 0)`}}><div className="grid h-32 w-32 place-items-center rounded-full bg-ink text-center"><div><b className="font-display text-4xl">{exposure.exposure_score}</b><p className="text-[10px] text-white/35">EXPOSURE SCORE</p></div></div></div><div className="grid grid-cols-2 gap-3">{[[Clock,"Outdoor limit",`${exposure.recommended_outdoor_limit} min`],[Activity,"Relative dose",exposure.relative_dose],[HeartPulse,"Risk class",exposure.risk],[ShieldCheck,"Best window",exposure.best_window]].map(([Icon,l,v])=><div className="rounded-xl bg-white/[.06] p-3" key={l as string}><Icon size={14} className="mb-3 text-mint"/><p className="text-[10px] text-white/35">{l as string}</p><b className="text-sm">{v as string|number}</b></div>)}</div></div><p className="mt-6 rounded-xl border border-mint/15 bg-mint/[.06] p-4 text-sm leading-6 text-white/65">{exposure.advice}</p></>}</section></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">{drift&&<ChartCard title="Feature drift radar" subtitle={`Overall drift ${drift.overall_drift}% · prediction drift ${drift.prediction_drift}%`} action={<span className={`rounded-full px-3 py-1 text-[10px] font-bold ${drift.retraining_required?"bg-orange-100 text-orange-700":"bg-emerald-100 text-emerald-700"}`}>{drift.model_health}</span>}><ResponsiveContainer width="100%" height={280}><BarChart data={drift.features} layout="vertical"><CartesianGrid horizontal={false} stroke="rgba(100,116,139,.1)"/><XAxis type="number" domain={[0,100]} tick={{fontSize:10}} axisLine={false}/><YAxis type="category" dataKey="feature" width={78} tick={{fontSize:10}} axisLine={false}/><Tooltip/><Bar dataKey="drift" radius={[0,7,7,0]}>{drift.features.map((x:any)=><Cell key={x.feature} fill={x.drift>20?"#f97316":"#10b981"}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard>}<section className="panel"><div className="flex items-center gap-3"><AlertTriangle className="text-amber-500"/><div><h3 className="font-display font-bold">Anomaly sentinel</h3><p className="text-xs text-slate-400">Robust deviation detection · Nagpur</p></div></div>{anomaly&&<><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-slate-400">Pattern status</p><b className="font-display text-xl">{anomaly.status}</b></div><span className="text-xs text-slate-400">Baseline {anomaly.baseline_aqi}</span></div><div className="mt-5 space-y-3">{anomaly.anomalies.slice(-3).map((x:any)=><div className="rounded-xl border border-emerald-950/10 p-3 dark:border-white/10" key={x.timestamp}><div className="flex justify-between"><b className="text-sm">AQI {x.aqi}</b><span className="text-[10px] font-bold text-amber-600">{x.severity}</span></div><p className="mt-1 text-xs text-slate-400">{x.change_from_baseline}% vs baseline · driver {x.probable_driver}</p></div>)}</div></>}</section></div>
    <section className="panel flex gap-4"><BrainCircuit className="shrink-0 text-emerald-600"/><p className="text-sm leading-6 text-slate-500"><b className="text-current">Safety principle:</b> personal exposure is a decision-support estimate, while drift monitoring protects against silent model degradation. Neither replaces official alerts or clinical advice.</p></section></div>;
}
