import { AlertTriangle, ArrowDownRight, CalendarDays, Clock3 } from "lucide-react";
import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { endpoints } from "../api/api";
import { ChartCard } from "../components/ChartCard";
import { aqiColor, shortDate } from "../utils/aqiUtils";

export default function Forecasting() {
  const [city,setCity]=useState("Nagpur");const [data,setData]=useState<any>();
  useEffect(()=>{setData(undefined);endpoints.forecast(city).then(setData)},[city]);
  return <div className="mx-auto max-w-7xl space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Forward atmospheric view</p><h2 className="mt-2 font-display text-3xl font-bold">Forecast lab</h2><p className="mt-2 text-sm text-slate-400">Anticipate exposure windows across the next 24 hours and seven days.</p></div><select className="input !w-44" value={city} onChange={e=>setCity(e.target.value)}>{["Nagpur","Pune","Mumbai","Delhi","Bengaluru","Hyderabad"].map(x=><option key={x}>{x}</option>)}</select></div>
    {!data?<div className="panel animate-pulse text-sm text-slate-400">Building forecast envelope…</div>:<>
      <div className="grid gap-4 md:grid-cols-3"><div className="panel"><Clock3 className="text-emerald-500"/><p className="mt-5 text-xs text-slate-400">24-hour peak</p><b className="font-display text-3xl">{Math.max(...data.hourly.map((x:any)=>x.aqi)).toFixed(0)} AQI</b></div><div className="panel"><ArrowDownRight className={data.trend==="improving"?"text-emerald-500":"rotate-180 text-orange-500"}/><p className="mt-5 text-xs text-slate-400">Seven-day direction</p><b className="font-display text-3xl capitalize">{data.trend}</b></div><div className={`panel ${data.alert?"!border-orange-300 !bg-orange-50 dark:!bg-orange-500/10":""}`}><AlertTriangle className={data.alert?"text-orange-500":"text-emerald-500"}/><p className="mt-5 text-xs text-slate-400">Exposure alert</p><b className="font-display text-lg">{data.message}</b></div></div>
      <ChartCard title="Next 24 hours" subtitle="Hourly AQI projection with diurnal dispersion pattern"><ResponsiveContainer width="100%" height={320}><AreaChart data={data.hourly}><defs><linearGradient id="forecastFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#10b981" stopOpacity=".35"/><stop offset="1" stopColor="#10b981" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(100,116,139,.1)"/><XAxis dataKey="time" tickFormatter={(x)=>new Date(x).toLocaleTimeString([],{hour:"2-digit"})} tick={{fontSize:10}} axisLine={false}/><YAxis axisLine={false} tick={{fontSize:10}}/><Tooltip labelFormatter={x=>new Date(x).toLocaleString()}/><Area type="monotone" dataKey="aqi" stroke="#10b981" strokeWidth={3} fill="url(#forecastFill)"/></AreaChart></ResponsiveContainer></ChartCard>
      <section className="panel"><div className="mb-5 flex items-center gap-3"><CalendarDays className="text-emerald-500"/><div><h3 className="font-display font-bold">Seven-day outlook</h3><p className="text-xs text-slate-400">Daily exposure classification</p></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{data.daily.map((day:any)=><div key={day.date} className="rounded-2xl border border-emerald-950/10 p-4 dark:border-white/10"><p className="text-xs text-slate-400">{shortDate(day.date)}</p><b className="mt-3 block font-display text-3xl">{day.aqi.toFixed(0)}</b><span className="mt-3 inline-block rounded-full px-2 py-1 text-[10px] font-bold" style={{color:aqiColor(day.aqi),background:`${aqiColor(day.aqi)}15`}}>{day.category}</span></div>)}</div></section></>}</div>;
}
