import { CheckCircle2, Download, FileBarChart, FileSpreadsheet } from "lucide-react";
import { useState } from "react";
import { api } from "../api/api";
import { defaultInput } from "../types";

export default function Reports(){
  const [city,setCity]=useState("Nagpur");const [busy,setBusy]=useState("");const [done,setDone]=useState("");
  const download=async(format:"pdf"|"csv")=>{setBusy(format);setDone("");try{const response=await api.post("/generate-report",{...defaultInput,city,format},{responseType:"blob"});const url=URL.createObjectURL(response.data);const a=document.createElement("a");a.href=url;a.download=`${city.toLowerCase()}-air-quality-report.${format}`;a.click();URL.revokeObjectURL(url);setDone(format)}finally{setBusy("")}};
  return <div className="mx-auto max-w-6xl space-y-5"><div><p className="eyebrow">Decision-ready evidence</p><h2 className="mt-2 font-display text-3xl font-bold">Reports center</h2><p className="mt-2 text-sm text-slate-400">Package model results, explanations and health guidance into portable evidence.</p></div>
    <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="panel"><FileBarChart className="text-emerald-600"/><h3 className="mt-6 font-display text-xl font-bold">Create a city report</h3><p className="mt-2 text-sm leading-6 text-slate-400">The PDF includes pollutant readings, model output, explainability, recommendations and a concluding assessment.</p><label className="mt-7 block text-xs font-semibold text-slate-500">Reporting city<select className="input mt-2" value={city} onChange={e=>setCity(e.target.value)}>{["Nagpur","Pune","Mumbai","Delhi","Bengaluru","Hyderabad"].map(x=><option key={x}>{x}</option>)}</select></label><button className="btn-primary mt-4 w-full" onClick={()=>download("pdf")}><Download size={17}/>{busy==="pdf"?"Generating PDF…":"Download intelligence report"}</button></section>
      <section className="rounded-[1.5rem] bg-ink p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-mint">Report preview</p><h3 className="mt-4 font-display text-3xl font-bold">Air Quality<br/>Intelligence Brief</h3><p className="mt-2 text-sm text-white/40">{city} · model-generated assessment</p><div className="mt-9 grid grid-cols-3 gap-3">{[["AQI","171"],["Category","Poor"],["Confidence","87%"]].map(([l,v])=><div className="rounded-2xl bg-white/[.06] p-4" key={l}><p className="text-[10px] text-white/35">{l}</p><b className="mt-1 block">{v}</b></div>)}</div><div className="mt-5 h-28 rounded-2xl bg-gradient-to-r from-emerald-400/10 to-orange-400/10 p-4"><div className="flex h-full items-end gap-2">{[35,52,48,68,45,78,61,84,55,72].map((x,i)=><i key={i} className="flex-1 rounded-t bg-mint/60" style={{height:`${x}%`}}/>)}</div></div><div className="mt-5 flex items-center gap-2 text-xs text-white/40"><CheckCircle2 size={14} className="text-mint"/> Explainability and audience health guidance included</div></section></div>
    <section className="panel flex flex-col justify-between gap-5 md:flex-row md:items-center"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-500/10 dark:text-mint"><FileSpreadsheet/></span><div><b>Structured data export</b><p className="text-sm text-slate-400">Download the prediction summary for spreadsheets and research workflows.</p></div></div><button className="btn-secondary shrink-0" onClick={()=>download("csv")}><Download size={16}/>{busy==="csv"?"Exporting…":"Export CSV"}</button></section>{done&&<p className="text-center text-sm text-emerald-600">Your {done.toUpperCase()} report was generated successfully.</p>}</div>;
}
