import { ArrowRight, FlaskConical, TrendingDown, WandSparkles } from "lucide-react";
import { useState } from "react";
import { endpoints } from "../api/api";
import { defaultInput, type AirInput } from "../types";

const controls:{key:keyof AirInput;label:string;max:number;unit:string}[]=[{key:"PM2.5",label:"Fine particles",max:250,unit:"µg/m³"},{key:"PM10",label:"Coarse particles",max:400,unit:"µg/m³"},{key:"NO2",label:"Nitrogen dioxide",max:200,unit:"µg/m³"},{key:"humidity",label:"Humidity",max:100,unit:"%"},{key:"temperature",label:"Temperature",max:50,unit:"°C"}];
export default function WhatIfAnalysis(){
  const [scenario,setScenario]=useState<AirInput>({...defaultInput});const [result,setResult]=useState<any>();const [busy,setBusy]=useState(false);
  const run=async()=>{setBusy(true);try{setResult(await endpoints.whatIf(defaultInput,scenario))}finally{setBusy(false)}};
  return <div className="mx-auto max-w-7xl space-y-5"><div><p className="eyebrow">Intervention modelling</p><h2 className="mt-2 font-display text-3xl font-bold">What-if studio</h2><p className="mt-2 text-sm text-slate-400">Move the atmospheric levers and quantify a cleaner-air scenario in real time.</p></div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="panel"><div className="mb-7 flex items-center gap-3"><FlaskConical className="text-emerald-600"/><div><h3 className="font-display font-bold">Scenario controls</h3><p className="text-xs text-slate-400">Baseline: Nagpur’s latest observation</p></div></div><div className="space-y-7">{controls.map(c=><label key={c.key} className="block"><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{c.label}</span><b className="rounded-lg bg-emerald-100 px-2 py-1 text-xs text-emerald-700 dark:bg-emerald-500/10 dark:text-mint">{scenario[c.key] as number} {c.unit}</b></div><input className="w-full accent-emerald-500" type="range" min="0" max={c.max} step={c.key==="temperature"?1:.5} value={scenario[c.key] as number} onChange={e=>setScenario({...scenario,[c.key]:Number(e.target.value)})}/><div className="flex justify-between text-[10px] text-slate-400"><span>0</span><span>{c.max}</span></div></label>)}</div><button className="btn-primary mt-8 w-full" onClick={run} disabled={busy}><WandSparkles size={17}/>{busy?"Simulating…":"Simulate this intervention"}</button></section>
      <section className="relative overflow-hidden rounded-[1.6rem] bg-ink p-7 text-white">{result?<><p className="text-xs uppercase tracking-[.18em] text-mint">Scenario impact</p><div className="mt-9 flex items-center justify-center gap-6"><div className="text-center"><p className="text-xs text-white/35">Before</p><b className="font-display text-5xl">{result.original.predicted_aqi.toFixed(0)}</b></div><ArrowRight className="text-mint"/><div className="text-center"><p className="text-xs text-white/35">After</p><b className="font-display text-5xl">{result.scenario.predicted_aqi.toFixed(0)}</b></div></div><div className={`mx-auto mt-8 flex w-fit items-center gap-2 rounded-full px-4 py-2 text-sm font-bold ${result.direction==="improvement"?"bg-emerald-400/10 text-mint":"bg-orange-400/10 text-orange-300"}`}><TrendingDown className={result.direction==="improvement"?"":"rotate-180"} size={17}/>{result.change_percent}% {result.direction}</div><div className="mt-8 rounded-2xl bg-white/[.06] p-5"><p className="text-xs font-bold uppercase tracking-widest text-white/40">Recommendation</p><p className="mt-3 leading-7 text-white/75">{result.recommendation}</p></div></>:<div className="grid h-full min-h-[500px] place-items-center text-center"><div><FlaskConical className="mx-auto text-white/20" size={40}/><h3 className="mt-5 font-display text-xl font-bold">Design an intervention</h3><p className="mt-2 max-w-xs text-sm leading-6 text-white/35">Adjust emissions or weather conditions, then run the simulator to compare outcomes.</p></div></div>}</section></div></div>;
}
